### ISSUE TITLE
MessagePackSerializer.Typeless needs a Deserialize(ArraySegment<byte>)

### ISSUE THREAD

**Issue by AbhitejJohn** [AArnott/MessagePack-CSharp#19]
It looks like the Typeless serializer does not have all the overloads that MessagePackSerializer does especially the overload with ArraySegment.

**Comment by AArnott** [comment]
You know that typeless class is just syntax sugar for `Deserialize<object>`, right?
That, and the `TypelessContractlessStandardResolver` is specified in the constructor.

**Comment by AArnott** [comment]
Honestly, I don't know if it's worth maintaining a separate replicate type for such a simple bit of syntax sugar.

**Comment by AbhitejJohn** [comment]
That's right, thought abstracting away the `TypelessContractlessStandardResolver` was pretty neat for most usage. Perhaps there is a better way of specifying this - maybe through a capability instead.

**Comment by AArnott** [comment]
OK, I guess the biggest problem with removing the `Typeless` class is that it's important to explicitly use `object` as the generic type argument to `Serialize`, otherwise `Deserialize` doesn't know what type to deserialize when using `<object>`.
