### ISSUE TITLE
Greater DataContractSerializer compatibility

### ISSUE THREAD

**Issue by AArnott** [AArnott/MessagePack-CSharp#22]
no existing resolver can simulate DataContractSerializer.
ex:
```
[DataContract]
public class Master {
    [DataMember]
    public string A { get; set; }
    [DataMember]
    internal Detail B { get; set; }
}
public class Detail {
    public string B1 { get; set; }
    internal string B2 { get; set; }
}
```

The original `DataContractSerializer`, includes A, B and B1.
The `ContractlessStandardResolver` only includes A.
The `ContractlessStandardResolverAllowPrivate`, include A, B and B1 and B2.

_Originally posted by @fredliex in https://github.com/AArnott/MessagePack-CSharp/issues/18#issuecomment-447622268_

**Comment by AArnott** [comment]
I'm working on a test to repro this.

**Comment by peterwald** [comment]
It would be very helpful if we can also handle internal `[DataContract]` classes with internal `[DataMember]` properties as well.

```csharp
[DataContract]
internal class Master {
    [DataMember]
    internal string A { get; set; }
    [IgnoreDataMember]
    internal string B { get; set; }
}
```

**Comment by AArnott** [comment]
Internal classes *might* work, depending on the real outcome of https://github.com/neuecc/MessagePack-CSharp/issues/88

**Comment by AArnott** [comment]
If this isn't already working in 2.0, please open a new issue on the root project (not my fork).
