### ISSUE TITLE
Fix perf from resolver lookup

### ISSUE THREAD

**Issue by AArnott** [AArnott/MessagePack-CSharp#48]
The fact that every little write operation goes through a resolver is killing perf. In PerfNetFramework, the single biggest frame when measuring exclusive time is related to formatter lookup, which takes up nearly 1/3 of the time:

Name | Inc % | Inc
-- | -- | --
| clr!JIT_VirtualFunctionPointer | 31.7 | 45
|+ messagepack!FormatterResolverExtensions.GetFormatterWithVerify | 31.7 | 45
|+ messagepack.resolvers.dynamicobjectresolver!PerfNetFramework_PersonFormatter1.Serialize | 31.7 | 45

This is an incredible opportunity to improve performance if we can get rid of this. 

But resolvers provide the vital functionality of being able to customize how types are serialized. How to resolve this?

## Proposal

Quit using resolvers for primitive types. ~Delete those resolvers and~ modify the rest of them to call directly into the `MessagePackWriter` / `MessagePackReader` structs to write primitives. This alone should dramatically decrease the time spent calling into resolvers.

(We can't delete the primitive resolvers because they are needed when serializing primitives as top-level objects).

**Comment by neuecc** [comment]
> Quit using resolvers for primitive types

I know it, so v1.x already implemented like it.
https://github.com/neuecc/MessagePack-CSharp/blob/master/src/MessagePack/Resolvers/DynamicObjectResolver.cs#L1168-L1191

**Comment by AArnott** [comment]
Interesting. I remember that code now that you mention it. Even so, 32% of the perf problem remains. I see you exclude a few types: 

https://github.com/AArnott/MessagePack-CSharp/blob/c55ad18990396e90c02833ee4c8236e8e8770de4/src/MessagePack/Resolvers/DynamicObjectResolver.cs#L1109-L1112

I suppose that's so that the OldSpec resolver (if present) can change how it's written. For PerfNetFramework if I decompile the dynamic assembly, these are the calls to get a formatter:

```cs
	P_1 += P_3.GetFormatterWithVerify<string>().Serialize(ref P_0, P_1, P_2.FirstName, P_3);
	P_1 += P_3.GetFormatterWithVerify<string>().Serialize(ref P_0, P_1, P_2.LastName, P_3);
	P_1 += P_3.GetFormatterWithVerify<Sex>().Serialize(ref P_0, P_1, P_2.Sex, P_3);
```

Two strings and an enum. The enum resolver call could be replaced with primitive writer/reader calls using the enum's underlying type. I see there are *two* enum resolvers, and one uses integers while the other uses strings. Is supporting names really important? I'm not sure how we can remove the dependency on the resolver for the enum so long as that option exists.

With my change in #42 to build OldSpec functionality into the writer itself instead of a resolver, the resolver for the 2 strings can be changed to just call the writer directly. That should at least cut down the perf hit by 2/3rds with no adverse effect on the user.

**Comment by AArnott** [comment]
Cool. When I make this few line change to add `string` to the optimized list, the #42 PR goes from being slightly slower than v1.8 to _faster_. Serialization goes from 104% to 96%, and deserialization goes from 109% to 86%. 
And that's just a couple runs. I expect serialization ought to improve more than just 8%.

And if we dared remove `EnumAsStringResolver` behavior, we could get this even faster.

**Comment by AArnott** [comment]
The only part of this issue that remains is an open question around the enum type handling, which we could remove the resolver for if we can give up by-name storing of enum values and use integers always.

**Comment by neuecc** [comment]
Enum to String is sometimes used in JSON.NET(`StringEnumConverter`).
I can not deny the demand for it too.

from continuation of last comment of #42,
WriteString is fairly heavy processing compare with write primitive values.
It is amortized, (but of-course benchmark score is down).
So I've invoked from Resolver for compatibility of OldSpec, I thought that I could compromise..
But for maximize performance, it is welcome to change string directly.
Nonetheless, I think that there is still should changed about OldSpec's setting method.

**Comment by AArnott** [comment]
OK, based on enum as string demand, I'll close this after having fixed the perf related to serializing strings and byte[].
